# Generated by Django 2.1.5 on 2026-03-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'items_cosmetic',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'items_hero',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'items_item',
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisation.Item')),
            ],
            options={
                'db_table': 'items_pricerecord',
            },
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisation.Hero'),
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualisation.Item'),
        ),
    ]
